on: workflow_dispatch

jobs:
  k6-browser:

    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
      
      # - name: Set env
      #   run: echo "K6_BROWSER_ENABLED=true" >> $GITHUB_ENV

      - name: Docker Build
        run: docker build -t k6 .

      - name: Run Browser Test
        run: docker run -v ./:/tests/ testing-k6 run /tests/example.browser.test.js
