on: workflow_dispatch

jobs:
  k6-browser:

    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout
        uses: actions/checkout@v1
    
      - name: Download latest chromium
        run: sudo apt update && sudo apt install chromium-browser
      
      - name: Set env
        run: echo "K6_BROWSER_ENABLED=true" >> $GITHUB_ENV

      - name: Run local Browser k6 test
        uses: grafana/k6-action@v0.3.0
        with:
          filename: example.browser.test.js
        env:
          K6_BROWSER_ENABLED: true
